name: Test and release

on:
    push:
        branches:
        - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Test
      run: |
        echo "Running tests..."
        # Add your test commands here
        echo "Tests completed successfully."

  release:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main
          fallbackTag: v0.0.0

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          generateReleaseNotes: true
          tag: ${{ steps.semver.outputs.next }}
          body: Changelog Contents
          token: ${{ github.token }}